#
# PLAYTIME PLUGIN
# Made by Gura1
#
database:
  type: SQLite # MYSQL or SQLite (More coming soon)
  mysql:
    host: localhost
    port: 3306
    database-name: playtime
    username: 1234
    password: 1234