name: PlayTime
version: '1.0'
main: net.gura.playTime.PlayTime
api-version: '1.21'
load: POSTWORLD
authors: [ Gura ]
softdepend: [PlaceholderAPI]
description: Playtime minecraft plugin

commands:
  playtime:
    description: Playtime plugin command
    usage: /playtime <player> <set|delete> <player> [seconds]
    permission: playtime.admin

permissions:
  playtime.admin:
    description: Playtime admin permission
    default: op
  playtime.view:
    description: Playtime view own permission
    default: op
  playtime.view.others:
    description: Playtime view others permission
    default: op
